export const queryKeys = {
  auth: {
    me: ["auth", "me"] as const,
    sessions: ["auth", "sessions"] as const,
    roles: ["auth", "roles"] as const,
    permissions: ["auth", "permissions"] as const,
  },
  organizations: {
    list: ["organizations", "list"] as const,
    detail: (organizationId: string) => ["organizations", organizationId] as const,
    settings: (organizationId: string) => ["organizations", organizationId, "settings"] as const,
    members: (organizationId: string) => ["organizations", organizationId, "members"] as const,
  },
  notifications: {
    list: (organizationId: string) => ["notifications", organizationId, "list"] as const,
    unreadCount: (organizationId: string) => ["notifications", organizationId, "unread-count"] as const,
  },
  accounts: {
    root: (organizationId: string) => ["accounts", organizationId] as const,
    list: (organizationId: string, search = "") => ["accounts", organizationId, "list", search] as const,
    detail: (organizationId: string, accountId: string) => ["accounts", organizationId, "detail", accountId] as const,
    balance: (organizationId: string, accountId: string) => ["accounts", organizationId, "balance", accountId] as const,
    ledger: (organizationId: string, accountId: string) => ["accounts", organizationId, "ledger", accountId] as const,
  },
  banking: {
    bankAccountsRoot: (organizationId: string) => ["bank-accounts", organizationId] as const,
    bankAccounts: (organizationId: string, search = "") => ["bank-accounts", organizationId, "list", search] as const,
    bankAccount: (organizationId: string, bankAccountId: string) => ["bank-accounts", organizationId, "detail", bankAccountId] as const,
    bankAccountSummary: (organizationId: string, bankAccountId: string) => ["bank-accounts", organizationId, "summary", bankAccountId] as const,
    bankAccountRegister: (organizationId: string, bankAccountId: string) => ["bank-accounts", organizationId, "register", bankAccountId] as const,
    bankImports: (organizationId: string) => ["bank-imports", organizationId, "list"] as const,
    bankImport: (organizationId: string, importId: string) => ["bank-imports", organizationId, "detail", importId] as const,
    bankImportTransactions: (organizationId: string, importId: string) => ["bank-imports", organizationId, "transactions", importId] as const,
    bankTransactionsRoot: (organizationId: string) => ["bank-transactions", organizationId] as const,
    bankTransactions: (organizationId: string, search = "") => ["bank-transactions", organizationId, "list", search] as const,
    bankTransaction: (organizationId: string, transactionId: string) => ["bank-transactions", organizationId, "detail", transactionId] as const,
    bankTransactionSuggestions: (organizationId: string, transactionId: string) => ["bank-transactions", organizationId, "suggestions", transactionId] as const,
    reconciliations: (organizationId: string) => ["reconciliations", organizationId, "list"] as const,
    reconciliation: (organizationId: string, reconciliationId: string) => ["reconciliations", organizationId, "detail", reconciliationId] as const,
    bankRules: (organizationId: string) => ["bank-rules", organizationId, "list"] as const,
    bankRule: (organizationId: string, ruleId: string) => ["bank-rules", organizationId, "detail", ruleId] as const,
    cashbook: (organizationId: string) => ["cashbook", organizationId] as const,
    reconciliationSummary: (organizationId: string) => ["reconciliation-summary", organizationId] as const,
  },
  reporting: {
    root: (organizationId: string) => ["reports", organizationId] as const,
    metadata: (organizationId: string) => ["reports", organizationId, "metadata"] as const,
    trialBalance: (organizationId: string, filters: Record<string, unknown>) => ["reports", organizationId, "trial-balance", filters] as const,
    profitLoss: (organizationId: string, filters: Record<string, unknown>) => ["reports", organizationId, "profit-loss", filters] as const,
    balanceSheet: (organizationId: string, filters: Record<string, unknown>) => ["reports", organizationId, "balance-sheet", filters] as const,
    generalLedger: (organizationId: string, filters: Record<string, unknown>) => ["reports", organizationId, "general-ledger", filters] as const,
  },
  settings: {
    root: (organizationId: string) => ["settings", organizationId] as const,
    organization: (organizationId: string) => ["settings", organizationId, "organization"] as const,
    fiscalPeriods: (organizationId: string) => ["settings", organizationId, "fiscal-periods"] as const,
    fiscalPeriod: (organizationId: string, periodId: string) => ["settings", organizationId, "fiscal-periods", periodId] as const,
    taxCodes: (organizationId: string) => ["settings", organizationId, "tax-codes"] as const,
    taxCode: (organizationId: string, taxCodeId: string) => ["settings", organizationId, "tax-codes", taxCodeId] as const,
    documentSettings: (organizationId: string) => ["settings", organizationId, "document-settings"] as const,
    accountingSettings: (organizationId: string) => ["settings", organizationId, "accounting-settings"] as const,
  },
  suppliers: {
    root: (organizationId: string) => ["suppliers", organizationId] as const,
    list: (organizationId: string, search = "") => ["suppliers", organizationId, "list", search] as const,
    detail: (organizationId: string, supplierId: string) => ["suppliers", organizationId, "detail", supplierId] as const,
    balance: (organizationId: string, supplierId: string) => ["suppliers", organizationId, "balance", supplierId] as const,
    activity: (organizationId: string, supplierId: string) => ["suppliers", organizationId, "activity", supplierId] as const,
  },
  bills: {
    root: (organizationId: string) => ["bills", organizationId] as const,
    list: (organizationId: string, search = "") => ["bills", organizationId, "list", search] as const,
    open: (organizationId: string) => ["bills", organizationId, "open"] as const,
    overdue: (organizationId: string) => ["bills", organizationId, "overdue"] as const,
    detail: (organizationId: string, billId: string) => ["bills", organizationId, "detail", billId] as const,
    attachments: (organizationId: string, billId: string) => ["bills", organizationId, "attachments", billId] as const,
  },
  customers: {
    root: (organizationId: string) => ["customers", organizationId] as const,
    list: (organizationId: string, search = "") => ["customers", organizationId, "list", search] as const,
    detail: (organizationId: string, customerId: string) => ["customers", organizationId, "detail", customerId] as const,
    balance: (organizationId: string, customerId: string) => ["customers", organizationId, "balance", customerId] as const,
    activity: (organizationId: string, customerId: string) => ["customers", organizationId, "activity", customerId] as const,
  },
  invoices: {
    root: (organizationId: string) => ["invoices", organizationId] as const,
    list: (organizationId: string, search = "") => ["invoices", organizationId, "list", search] as const,
    open: (organizationId: string) => ["invoices", organizationId, "open"] as const,
    overdue: (organizationId: string) => ["invoices", organizationId, "overdue"] as const,
    detail: (organizationId: string, invoiceId: string) => ["invoices", organizationId, "detail", invoiceId] as const,
    attachments: (organizationId: string, invoiceId: string) => ["invoices", organizationId, "attachments", invoiceId] as const,
  },
  journals: {
    root: (organizationId: string) => ["journals", organizationId] as const,
    list: (organizationId: string, search = "") => ["journals", organizationId, "list", search] as const,
    detail: (organizationId: string, journalId: string) => ["journals", organizationId, "detail", journalId] as const,
  },
  periods: {
    root: (organizationId: string) => ["periods", organizationId] as const,
    list: (organizationId: string) => ["periods", organizationId, "list"] as const,
    detail: (organizationId: string, periodId: string) => ["periods", organizationId, "detail", periodId] as const,
  },
};
