export type BankAccountType = "checking" | "savings" | "credit_card" | "cash" | "other";
export type BankImportStatus = "processing" | "completed" | "failed" | "partially_completed";
export type BankTransactionStatus = "unreconciled" | "suggested" | "matched" | "reconciled" | "ignored";
export type BankTransactionDirection = "money_in" | "money_out";
export type ReconciliationActionType = "match_customer_payment" | "match_supplier_payment" | "match_journal" | "cash_code" | "transfer";

export type RawBankAccount = {
  id: string;
  organization_id?: string;
  organizationId?: string;
  account_id?: string;
  accountId?: string;
  gl_account_id?: string;
  glAccountId?: string;
  gl_account_code?: string | null;
  glAccountCode?: string | null;
  gl_account_name?: string | null;
  glAccountName?: string | null;
  name?: string;
  display_name?: string | null;
  displayName?: string | null;
  bank_name?: string | null;
  bankName?: string | null;
  account_number_mask?: string | null;
  accountNumberMask?: string | null;
  account_number_masked?: string | null;
  accountNumberMasked?: string | null;
  iban_masked?: string | null;
  ibanMasked?: string | null;
  currency_code?: string | null;
  currencyCode?: string | null;
  account_type?: string | null;
  accountType?: string | null;
  opening_balance?: string | number | null;
  openingBalance?: string | number | null;
  opening_balance_date?: string | null;
  openingBalanceDate?: string | null;
  is_active?: boolean;
  isActive?: boolean;
  is_default_receipts_account?: boolean;
  isDefaultReceiptsAccount?: boolean;
  is_default_payments_account?: boolean;
  isDefaultPaymentsAccount?: boolean;
  feed_status?: string | null;
  feedStatus?: string | null;
  last_imported_at?: string | null;
  lastImportedAt?: string | null;
  last_reconciled_at?: string | null;
  lastReconciledAt?: string | null;
  created_at?: string | null;
  createdAt?: string | null;
  updated_at?: string | null;
  updatedAt?: string | null;
};

export type BankAccount = {
  id: string;
  organizationId?: string;
  glAccountId: string;
  glAccountCode?: string | null;
  glAccountName?: string | null;
  name: string;
  displayName?: string | null;
  bankName?: string | null;
  accountNumberMasked?: string | null;
  ibanMasked?: string | null;
  currencyCode: string;
  accountType?: string | null;
  openingBalance: string;
  openingBalanceDate?: string | null;
  isActive: boolean;
  isDefaultReceiptsAccount: boolean;
  isDefaultPaymentsAccount: boolean;
  feedStatus?: string | null;
  lastImportedAt?: string | null;
  lastReconciledAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
};

export type BankAccountSummary = {
  bankAccountId: string;
  openingBalance: string;
  ledgerBalance: string;
  unreconciledDelta: string;
  availableBalance?: string | null;
  unreconciledCount?: number | null;
  reconciledCount?: number | null;
  ignoredCount?: number | null;
};

export type BankRegisterLine = {
  id: string;
  transactionDate: string;
  postedDate?: string | null;
  description: string;
  reference?: string | null;
  amount: string;
  runningBalance?: string | null;
  status?: BankTransactionStatus | string | null;
};

export type RawBankImport = {
  id: string;
  organization_id?: string;
  organizationId?: string;
  bank_account_id?: string | null;
  bankAccountId?: string | null;
  bank_account_name?: string | null;
  bankAccountName?: string | null;
  source?: string | null;
  file_name?: string | null;
  fileName?: string | null;
  imported_at?: string | null;
  importedAt?: string | null;
  status?: string | null;
  total_lines?: number | null;
  totalLines?: number | null;
  imported_lines?: number | null;
  importedLines?: number | null;
  duplicate_lines?: number | null;
  duplicateLines?: number | null;
  failed_lines?: number | null;
  failedLines?: number | null;
  notes?: string | null;
};

export type BankImport = {
  id: string;
  organizationId?: string;
  bankAccountId?: string | null;
  bankAccountName?: string | null;
  source?: string | null;
  fileName?: string | null;
  importedAt?: string | null;
  status: string;
  totalLines?: number | null;
  importedLines?: number | null;
  duplicateLines?: number | null;
  failedLines?: number | null;
  notes?: string | null;
};

export type RawBankTransaction = {
  id: string;
  organization_id?: string;
  organizationId?: string;
  bank_account_id?: string;
  bankAccountId?: string;
  bank_account_name?: string | null;
  bankAccountName?: string | null;
  transaction_date?: string;
  transactionDate?: string;
  posted_date?: string | null;
  postedDate?: string | null;
  transaction_type?: string | null;
  transactionType?: string | null;
  amount?: string | number;
  description?: string | null;
  payee?: string | null;
  reference?: string | null;
  memo?: string | null;
  notes?: string | null;
  status?: string | null;
  matched_journal_id?: string | null;
  matchedJournalId?: string | null;
  matched_entity_type?: string | null;
  matchedEntityType?: string | null;
  matched_entity_id?: string | null;
  matchedEntityId?: string | null;
  source_module?: string | null;
  sourceModule?: string | null;
  source_type?: string | null;
  sourceType?: string | null;
  source_id?: string | null;
  sourceId?: string | null;
  target_account_id?: string | null;
  targetAccountId?: string | null;
  target_account_code?: string | null;
  targetAccountCode?: string | null;
  target_account_name?: string | null;
  targetAccountName?: string | null;
  tax_code_id?: string | null;
  taxCodeId?: string | null;
  currency_code?: string | null;
  currencyCode?: string | null;
  taxable_amount?: string | number | null;
  taxableAmount?: string | number | null;
  tax_amount?: string | number | null;
  taxAmount?: string | number | null;
  gross_amount?: string | number | null;
  grossAmount?: string | number | null;
  running_balance?: string | number | null;
  runningBalance?: string | number | null;
  duplicate_detected?: boolean | null;
  duplicateDetected?: boolean | null;
  suggestion_count?: number | null;
  suggestionCount?: number | null;
  reconciled_at?: string | null;
  reconciledAt?: string | null;
  reconciled_by?: string | null;
  reconciledBy?: string | null;
  reconciled_by_user_id?: string | null;
  reconciledByUserId?: string | null;
  created_at?: string | null;
  createdAt?: string | null;
  updated_at?: string | null;
  updatedAt?: string | null;
};

export type BankTransaction = {
  id: string;
  organizationId?: string;
  bankAccountId: string;
  bankAccountName?: string | null;
  transactionDate: string;
  postedDate?: string | null;
  transactionType?: string | null;
  amount: string;
  description: string;
  payee?: string | null;
  reference?: string | null;
  memo?: string | null;
  notes?: string | null;
  status: string;
  matchedJournalId?: string | null;
  matchedEntityType?: string | null;
  matchedEntityId?: string | null;
  sourceModule?: string | null;
  sourceType?: string | null;
  sourceId?: string | null;
  targetAccountId?: string | null;
  targetAccountCode?: string | null;
  targetAccountName?: string | null;
  taxCodeId?: string | null;
  currencyCode?: string | null;
  taxableAmount?: string | null;
  taxAmount?: string | null;
  grossAmount?: string | null;
  runningBalance?: string | null;
  duplicateDetected: boolean;
  suggestionCount?: number | null;
  reconciledAt?: string | null;
  reconciledBy?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
};

export type BankSuggestion = {
  id: string;
  type: string;
  label: string;
  reason?: string | null;
  score?: number | null;
  entityId?: string | null;
  entityType?: string | null;
  amount?: string | null;
  currencyCode?: string | null;
};

export type ReconciliationRecord = {
  id: string;
  organizationId?: string;
  bankTransactionId: string;
  bankTransactionDescription?: string | null;
  actionType?: string | null;
  matchedEntityType?: string | null;
  matchedEntityId?: string | null;
  createdJournalId?: string | null;
  createdAt?: string | null;
  createdBy?: string | null;
  status?: string | null;
};

export type BankRule = {
  id: string;
  organizationId?: string;
  name: string;
  isActive: boolean;
  priority?: number | null;
  appliesToBankAccountId?: string | null;
  matchPayeeContains?: string | null;
  matchDescriptionContains?: string | null;
  matchReferenceContains?: string | null;
  matchAmountExact?: string | null;
  matchAmountMin?: string | null;
  matchAmountMax?: string | null;
  direction?: string | null;
  actionType?: string | null;
  targetAccountId?: string | null;
  autoReconcile: boolean;
  notes?: string | null;
};

export type CashbookSummary = {
  bankAccountId?: string | null;
  bankAccountName?: string | null;
  glAccountId?: string | null;
  openingBalance?: string | null;
  ledgerBalance?: string | null;
  unreconciledDelta?: string | null;
};

export type ReconciliationSummary = {
  unreconciledCount?: number | null;
  reconciledCount?: number | null;
  ignoredCount?: number | null;
  latestImportedAt?: string | null;
};

export type BankAccountMutationPayload = {
  name: string;
  display_name?: string | null;
  bank_name?: string | null;
  account_number_masked?: string | null;
  iban_masked?: string | null;
  currency_code: string;
  account_type?: string | null;
  gl_account_id: string;
  opening_balance?: string | null;
  opening_balance_date?: string | null;
  is_active?: boolean;
  is_default_receipts_account?: boolean;
  is_default_payments_account?: boolean;
};

export type BankImportMutationPayload = {
  bank_account_id: string;
  file: File;
  source?: string | null;
  mapping_json?: string | null;
};

export type ReconciliationMutationPayload = Record<string, unknown>;

export type BankRuleMutationPayload = {
  name: string;
  is_active?: boolean;
  priority?: number | null;
  applies_to_bank_account_id?: string | null;
  match_payee_contains?: string | null;
  match_description_contains?: string | null;
  match_reference_contains?: string | null;
  match_amount_exact?: string | null;
  match_amount_min?: string | null;
  match_amount_max?: string | null;
  direction?: string | null;
  action_type: string;
  target_account_id?: string | null;
  auto_reconcile?: boolean;
  notes?: string | null;
};
