export const ROLE_PERMISSION_DEFAULTS = {
  owner: [
    "org.read", "org.update", "org.delete", "users.invite", "users.remove", "users.read", "roles.read", "settings.read", "settings.update",
    "accounts.create", "accounts.read", "accounts.update", "accounts.archive", "journals.create", "journals.read", "journals.update", "journals.post", "journals.reverse", "journals.void", "periods.create", "periods.read", "periods.update", "periods.close", "periods.lock", "periods.reopen", "ledger.read", "trial_balance.read",
    "customers.create", "customers.read", "customers.update", "customers.archive", "invoices.create", "invoices.read", "invoices.update", "invoices.approve", "invoices.send", "invoices.post", "invoices.void", "credit_notes.create", "credit_notes.read", "credit_notes.update", "credit_notes.post", "credit_notes.apply", "customer_payments.create", "customer_payments.read", "customer_payments.post", "customer_payments.allocate", "ar.read", "ar_aging.read",
    "suppliers.create", "suppliers.read", "suppliers.update", "suppliers.archive", "bills.create", "bills.read", "bills.update", "bills.approve", "bills.post", "bills.void", "supplier_credits.create", "supplier_credits.read", "supplier_credits.update", "supplier_credits.post", "supplier_credits.apply", "supplier_payments.create", "supplier_payments.read", "supplier_payments.post", "supplier_payments.allocate", "ap.read", "ap_aging.read",
    "reports.profit_loss.read", "reports.balance_sheet.read", "reports.trial_balance.read", "reports.general_ledger.read", "reports.account_statement.read", "reports.aged_receivables.read", "reports.aged_payables.read", "reports.export",
    "tax.settings.read", "tax.settings.update", "tax_rates.create", "tax_rates.read", "tax_rates.update", "tax_rates.archive", "tax_codes.create", "tax_codes.read", "tax_codes.update", "tax_codes.archive", "tax_reports.read", "tax_reports.export",
    "branding.read", "branding.update", "numbering.read", "numbering.update", "files.upload", "files.read", "files.delete", "files.link", "files.unlink", "email_templates.create", "email_templates.read", "email_templates.update", "emails.send", "emails.read", "notifications.read", "notifications.update", "notification_settings.read", "notification_settings.update",
    "bank_accounts.create", "bank_accounts.read", "bank_accounts.update", "bank_transactions.create", "bank_transactions.read", "bank_transactions.update", "bank_reconciliation.read", "bank_reconciliation.reconcile"
  ],
  admin: [
    "org.read", "org.update", "org.delete", "users.invite", "users.remove", "users.read", "roles.read", "settings.read", "settings.update",
    "accounts.create", "accounts.read", "accounts.update", "accounts.archive", "journals.create", "journals.read", "journals.update", "journals.post", "journals.reverse", "journals.void", "periods.create", "periods.read", "periods.update", "periods.close", "periods.lock", "ledger.read", "trial_balance.read",
    "customers.create", "customers.read", "customers.update", "customers.archive", "invoices.create", "invoices.read", "invoices.update", "invoices.approve", "invoices.send", "invoices.post", "invoices.void", "credit_notes.create", "credit_notes.read", "credit_notes.update", "credit_notes.post", "credit_notes.apply", "customer_payments.create", "customer_payments.read", "customer_payments.post", "customer_payments.allocate", "ar.read", "ar_aging.read",
    "suppliers.create", "suppliers.read", "suppliers.update", "suppliers.archive", "bills.create", "bills.read", "bills.update", "bills.approve", "bills.post", "bills.void", "supplier_credits.create", "supplier_credits.read", "supplier_credits.update", "supplier_credits.post", "supplier_credits.apply", "supplier_payments.create", "supplier_payments.read", "supplier_payments.post", "supplier_payments.allocate", "ap.read", "ap_aging.read",
    "reports.profit_loss.read", "reports.balance_sheet.read", "reports.trial_balance.read", "reports.general_ledger.read", "reports.account_statement.read", "reports.aged_receivables.read", "reports.aged_payables.read", "reports.export",
    "tax.settings.read", "tax.settings.update", "tax_rates.create", "tax_rates.read", "tax_rates.update", "tax_rates.archive", "tax_codes.create", "tax_codes.read", "tax_codes.update", "tax_codes.archive", "tax_reports.read", "tax_reports.export",
    "branding.read", "branding.update", "numbering.read", "numbering.update", "files.upload", "files.read", "files.delete", "files.link", "files.unlink", "email_templates.create", "email_templates.read", "email_templates.update", "emails.send", "emails.read", "notifications.read", "notifications.update", "notification_settings.read", "notification_settings.update",
    "bank_accounts.create", "bank_accounts.read", "bank_accounts.update", "bank_transactions.create", "bank_transactions.read", "bank_transactions.update", "bank_reconciliation.read", "bank_reconciliation.reconcile"
  ],
  accountant: [
    "accounts.create", "accounts.read", "accounts.update", "accounts.archive", "ap.read", "ap_aging.read", "ar.read", "ar_aging.read", "bank_accounts.create", "bank_accounts.read", "bank_accounts.update", "bank_reconciliation.read", "bank_reconciliation.reconcile", "bank_transactions.create", "bank_transactions.read", "bank_transactions.update", "bills.approve", "bills.create", "bills.post", "bills.read", "bills.update", "bills.void", "branding.read", "branding.update", "credit_notes.apply", "credit_notes.create", "credit_notes.post", "credit_notes.read", "credit_notes.update", "customer_payments.allocate", "customer_payments.create", "customer_payments.post", "customer_payments.read", "customers.archive", "customers.create", "customers.read", "customers.update", "email_templates.read", "emails.read", "emails.send", "files.link", "files.read", "files.upload", "invoices.approve", "invoices.create", "invoices.post", "invoices.read", "invoices.send", "invoices.update", "invoices.void", "journals.create", "journals.post", "journals.read", "journals.reverse", "journals.update", "journals.void", "ledger.read", "notification_settings.read", "notifications.read", "numbering.read", "org.read", "org.update", "periods.close", "periods.create", "periods.lock", "periods.read", "periods.update", "reports.account_statement.read", "reports.aged_payables.read", "reports.aged_receivables.read", "reports.balance_sheet.read", "reports.export", "reports.general_ledger.read", "reports.profit_loss.read", "reports.trial_balance.read", "roles.read", "settings.read", "settings.update", "supplier_credits.apply", "supplier_credits.create", "supplier_credits.post", "supplier_credits.read", "supplier_credits.update", "supplier_payments.allocate", "supplier_payments.create", "supplier_payments.post", "supplier_payments.read", "suppliers.archive", "suppliers.create", "suppliers.read", "suppliers.update", "tax.settings.read", "tax.settings.update", "tax_codes.archive", "tax_codes.create", "tax_codes.read", "tax_codes.update", "tax_rates.archive", "tax_rates.create", "tax_rates.read", "tax_rates.update", "tax_reports.export", "tax_reports.read", "users.invite", "users.read", "users.remove"
  ],
  staff: ["org.read", "customers.read", "invoices.create", "invoices.read", "invoices.update", "invoices.send", "suppliers.read", "bills.create", "bills.read", "bills.update", "accounts.read", "journals.read", "ledger.read", "bank_accounts.read", "bank_transactions.create", "bank_transactions.read", "bank_reconciliation.read", "files.upload", "files.read", "notifications.read", "notifications.update"],
  viewer: ["org.read", "customers.read", "invoices.read", "credit_notes.read", "customer_payments.read", "suppliers.read", "bills.read", "supplier_credits.read", "supplier_payments.read", "ar.read", "ar_aging.read", "ap.read", "ap_aging.read", "accounts.read", "journals.read", "ledger.read", "trial_balance.read", "reports.profit_loss.read", "reports.balance_sheet.read", "reports.trial_balance.read", "reports.general_ledger.read", "reports.account_statement.read", "reports.aged_receivables.read", "reports.aged_payables.read", "tax.settings.read", "tax_rates.read", "tax_codes.read", "tax_reports.read", "branding.read", "numbering.read", "notification_settings.read", "files.read", "notifications.read", "emails.read", "email_templates.read", "bank_accounts.read", "bank_transactions.read", "bank_reconciliation.read"],
} as const;

export type KnownRoleName = keyof typeof ROLE_PERMISSION_DEFAULTS;
